"""Synthetic, network-free tour of the real local v2 research contracts.

The discovery and ingestion observations below are explicitly SEEDED, not fetched from
an official source. The HTML is authored here, not scraped or redistributed. No model,
Jev, API key, real-world research assertion, or automated semantic judge is involved.
Run from the repository root: python -m examples.offline_walkthrough
"""

from __future__ import annotations

import json
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from research_pipeline.claim_evaluation import evaluate_case
from research_pipeline.claim_extraction import build_request, compile_response
from research_pipeline.discovery_state import (
    connect_state,
    record_success as record_discovery_success,
    start_run,
)
from research_pipeline.grounding import build_bundle, verify_bundle
from research_pipeline.ingestion import sha256_bytes, store_exact_object
from research_pipeline.ingestion_state import record_success as record_ingestion_success
from research_pipeline.normalization import normalize_ingestion_row

SOURCE_ID = "synthetic-demo"
URL = "https://example.com/research/synthetic-demo"
ENTRYPOINT = "https://example.com/research/"
FINDING = "Workers should receive scoped context for their tasks."

# Written for this example. The length and article structure exercise real Trafilatura
# extraction rather than constructing a normalized artifact by hand.
ARTICLE_HTML = f"""<!doctype html>
<html lang="en"><head><title>Synthetic Context Research</title>
<meta name="author" content="Example Author"></head>
<body><nav>Navigation is not article evidence.</nav><main><article>
<h1>Synthetic Context Research</h1>
<p>This wholly invented article illustrates evidence handling in a local research
pipeline. It has enough article prose to test real HTML extraction while making no
claim that any organization has published these words or endorsed this example.</p>
<p>The demonstration creates a local candidate and an immutable raw object. Its
purpose is to exercise provenance and citation contracts, not to test live crawling,
source authenticity, model quality, or the truth of an external publication.</p>
<h2>Finding</h2><p>{FINDING}</p>
<h2>Method</h2><p>All inputs are synthetic and produced within the example. A person has written
both the proposed claim and its illustrative review label. No model is consulted,
and a passing citation check does not confer semantic truth or doctrine status.</p>
</article></main><footer>Page chrome is not evidence.</footer></body></html>""".encode("utf-8")


def run_walkthrough(workspace: Path) -> dict:
    """Exercise the real offline contracts in a caller-owned scratch directory."""
    workspace = Path(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    state_path = workspace / "state.sqlite3"
    connection = connect_state(state_path)
    try:
        run_id = start_run(connection, SOURCE_ID)
        discovery = record_discovery_success(
            connection,
            run_id,
            [SimpleNamespace(entrypoint=ENTRYPOINT, candidates=[URL])],
        )
        raw_sha = sha256_bytes(ARTICLE_HTML)
        object_path = store_exact_object(state_path, raw_sha, ARTICLE_HTML)
        ingestion = record_ingestion_success(
            connection,
            source_id=SOURCE_ID,
            requested_url=URL,
            final_url=URL,
            content_type="text/html",
            bytes_read=len(ARTICLE_HTML),
            sha256=raw_sha,
            object_path=object_path,
        )
        row = connection.execute(
            "SELECT * FROM ingestion_observations WHERE id = ?",
            (ingestion.observation_id,),
        ).fetchone()
        normalized = normalize_ingestion_row(connection, row, state_path=state_path)
        if normalized.status != "SUCCESS" or not normalized.artifact_path:
            raise RuntimeError(f"synthetic normalization failed: {normalized.error}")
    finally:
        connection.close()

    artifact = json.loads((state_path.parent / normalized.artifact_path).read_text("utf-8"))
    blocks = [block for block in artifact["blocks"] if FINDING in block["text"]]
    if len(blocks) != 1:
        raise RuntimeError("synthetic finding must appear in exactly one citation block")

    bundle = build_bundle([(SOURCE_ID, URL, blocks[0]["ref"])], state_path=state_path)
    integrity = verify_bundle(bundle, state_path=state_path)
    request = build_request(bundle, state_path=state_path)
    evidence_id = bundle["items"][0]["evidence_id"]

    # Hand-authored fixture response. NOT generated by a model.
    response = {
        "schema_version": 1,
        "type": "claim_proposal_batch",
        "request_id": request["request_id"],
        "claims": [{"claim_text": FINDING, "citations": [evidence_id]}],
    }
    compiled = compile_response(response, request, bundle, state_path=state_path)
    candidate = compiled["candidates"][0]

    # An explicit illustrative human label, NOT an automated truth judgment.
    review = {
        "schema_version": 1,
        "type": "human_claim_review",
        "bundle_id": bundle["bundle_id"],
        "bundle_sha256": bundle["bundle_sha256"],
        "request_id": request["request_id"],
        "request_sha256": request["request_sha256"],
        "reviewer": "synthetic-example-author",
        "expected_findings": [{
            "finding_id": "f1",
            "required_evidence_ids": [evidence_id],
            "rationale": "The synthetic block contains the exact proposed sentence.",
        }],
        "judgments": [{
            "claim_id": candidate["claim_id"],
            "verdict": "supported",
            "finding_ids": ["f1"],
            "rationale": "Illustrative human-authored label, not a model assessment.",
        }],
    }
    evaluation = evaluate_case(bundle, request, response, review, state_path=state_path)

    return {
        "type": "synthetic_offline_walkthrough",
        "real_publication": False,
        "live_discovery_or_fetch": False,
        "model_or_jev_calls": 0,
        "source_id": SOURCE_ID,
        "requested_url": URL,
        "raw_sha256": raw_sha,
        "normalized_sha256": normalized.normalized_sha256,
        "citation_block_ref": blocks[0]["ref"],
        "bundle_id": bundle["bundle_id"],
        "request_id": request["request_id"],
        "citation_integrity": integrity["citation_integrity"],
        "candidate_status": candidate["status"],
        "semantic_support": evaluation["semantic_support"],
        "synthetic_supported_claim_precision": evaluation["supported_claim_precision"],
    }


def main() -> int:
    with TemporaryDirectory(prefix="research-pipeline-synthetic-") as scratch:
        result = run_walkthrough(Path(scratch))
        print(json.dumps(result, indent=2, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
